In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam
from keras import models,layers,metrics


In [ ]:
data = pd.read_fwf("/content/car.data", header=None)
data

0
0       vhigh,vhigh,2,2,small,low,unacc
1       vhigh,vhigh,2,2,small,med,unacc
2      vhigh,vhigh,2,2,small,high,unacc
3         vhigh,vhigh,2,2,med,low,unacc
4         vhigh,vhigh,2,2,med,med,unacc
...                                 ...
1723    low,low,5more,more,med,med,good
1724  low,low,5more,more,med,high,vgood
1725   low,low,5more,more,big,low,unacc
1726    low,low,5more,more,big,med,good
1727  low,low,5more,more,big,high,vgood

[1728 rows x 1 columns]

In [ ]:
a = []
for i in range(len(data)):
  a.append(data.iloc[i,0].split(','))

train_df = pd.DataFrame(a)
train_df.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [ ]:
col = ['buying' ,'maint','doors' ,'persons','lug_boot' ,'safety', 'Class'  ]
train_df.columns = col
train_df

buying  maint  doors persons lug_boot safety  Class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [ ]:
en = LabelEncoder()
for i in train_df.columns:
  train_df[i] = en.fit_transform(train_df[i])
train_df

buying  maint  doors  persons  lug_boot  safety  Class
0          3      3      0        0         2       1      3
1          3      3      0        0         2       2      3
2          3      3      0        0         2       0      3
3          3      3      0        0         1       1      3
4          3      3      0        0         1       2      3
...      ...    ...    ...      ...       ...     ...    ...
1723       1      1      3        2         1       2      1
1724       1      1      3        2         1       0      4
1725       1      1      3        2         0       1      3
1726       1      1      3        2         0       2      1
1727       1      1      3        2         0       0      4

[1728 rows x 7 columns]

In [ ]:
X = train_df.drop('Class', axis =1)
y = train_df['Class']

In [ ]:
y_1 = to_categorical(y)

In [ ]:
X_train,X_test, y_train,y_test = train_test_split(X,y_1,test_size=0.2,random_state=0)


In [ ]:
model = Sequential()

model.add(Dense(6,input_shape=(6,),activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(6,activation='relu'))
model.add(Dense(5,activation='sigmoid'))

model.compile(Adam(learning_rate=0.02),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_17"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_65 (Dense)            (None, 6)                 42        
                                                                 
 dense_66 (Dense)            (None, 6)                 42        
                                                                 
 dense_67 (Dense)            (None, 6)                 42        
                                                                 
 dense_68 (Dense)            (None, 5)                 35        
                                                                 
Total params: 161 (644.00 Byte)
Trainable params: 161 (644.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model_history=model.fit(x=X_train, y=y_train, epochs=100, batch_size=32,validation_data= (X_test,y_test))
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/100
44/44 [==============================] - 1s 7ms/step - loss: 1.2933 - accuracy: 0.6614 - val_loss: 1.0173 - val_accuracy: 0.6936
Epoch 2/100
44/44 [==============================] - 0s 3ms/step - loss: 0.8504 - accuracy: 0.7004 - val_loss: 0.7060 - val_accuracy: 0.6965
Epoch 3/100
44/44 [==============================] - 0s 3ms/step - loss: 0.6919 - accuracy: 0.6795 - val_loss: 0.7859 - val_accuracy: 0.6936
Epoch 4/100
44/44 [==============================] - 0s 3ms/step - loss: 0.6829 - accuracy: 0.6802 - val_loss: 0.6497 - val_accuracy: 0.6936
Epoch 5/100
44/44 [==============================] - 0s 3ms/step - loss: 0.6380 - accuracy: 0.7026 - val_loss: 0.6109 - val_accuracy: 0.6994
Epoch 6/100
44/44 [==============================] - 0s 3ms/step - loss: 0.6052 - accuracy: 0.7012 - val_loss: 0.6273 - val_accuracy: 0.7023
Epoch 7/100
44/44 [==============================] - 0s 3ms/step - loss: 0.5445 - accuracy: 0.7598 - val_loss: 0.5011 - val_accuracy: 0.7861
Epoch 8/100
4

In [ ]:
#Accuracy of the predicted values
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       0.91      0.85      0.88        79
           1       0.56      0.59      0.57        17
           3       0.99      0.97      0.98       240
           4       0.47      0.90      0.62        10

    accuracy                           0.92       346
   macro avg       0.73      0.83      0.76       346
weighted avg       0.94      0.92      0.93       346

[[ 67   7   2   3]
 [  0  10   0   7]
 [  7   0 233   0]
 [  0   1   0   9]]


In [ ]:
a =0
for i,j in zip(y_test_class,y_pred_class):
  if i == j:
    a +=1


print((a/len(y_pred_class))*100)

92.1965317919075
